package application;

import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.layout.Pane;
import javafx.stage.FileChooser;
import javafx.stage.Modality;
import javafx.stage.Stage;

import java.io.File;

import com.jfoenix.controls.JFXButton;
import com.jfoenix.controls.JFXTextField;

import javafx.event.ActionEvent;

public class SampleController {

	// Event Listener on JFXButton.onAction
	int cnt = 0;
	@FXML
	private JFXTextField filePath;
	@FXML
	private Pane step1, step2, step3, step4;
	@FXML
	private JFXButton btnStep1, btnStep2, btnStep3, btnStep4;
	@FXML
	public void handleButtonAction(ActionEvent event) {
		// TODO Autogenerated
		if(event.getSource() == btnStep1) {
			step1.toFront();
			FileChooser fileChooser = new FileChooser();
			fileChooser.setTitle("Open Resource File");
			Stage dialog = new Stage();
			File f = fileChooser.showOpenDialog(dialog);
			String aFilePath = f.getAbsolutePath();
			filePath.setText(aFilePath);
			runPython rp = new runPython(aFilePath);
			Thread rpThread = new Thread(rp);
			rpThread.start();
			
		}
		if(event.getSource() == btnStep2) {
			step2.toFront();
		}
		if(event.getSource() == btnStep3) {
			step3.toFront();
			Stage dialog = new Stage();
			dialog.initModality(Modality.APPLICATION_MODAL); 
			dialog.showAndWait();
			
		}
		if(event.getSource() == btnStep4) {
			step4.toFront();
		}
	}
}
