package application;

import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.layout.Pane;

import com.jfoenix.controls.JFXButton;

import javafx.event.ActionEvent;

public class SampleController {

	// Event Listener on JFXButton.onAction
	int cnt = 0;
	@FXML
	private Pane step1, step2, step3, step4;
	@FXML
	private JFXButton btnStep1, btnStep2, btnStep3, btnStep4;
	@FXML
	public void handleButtonAction(ActionEvent event) {
		// TODO Autogenerated
		if(event.getSource() == btnStep1) {
			step1.toFront();
			runPython rp = new runPython("speech_to_text.py");
			Thread rpThread = new Thread(rp);
			rpThread.start();
		}
		if(event.getSource() == btnStep2) {
			step2.toFront();
		}
		if(event.getSource() == btnStep3) {
			step3.toFront();
		}
		if(event.getSource() == btnStep4) {
			step4.toFront();
		}
	}
}
